### ISSUE TITLE
Ability to flip symbols

### ISSUE THREAD

**Issue by fariadiego** [devinmancuso/sketch-rtl#5]
Hey guys,
The plugin works fine here, but unfortunately I can't flip symbols :/
As the use of symbols is becoming very popular with the recent versions of Sketch, you should consider flipping symbols as well.

**Comment by mageframe** [comment]
+1 I'd like to include this in the next release. 
Would you imagine this just using the 'Flip horizontal' command on all symbols, or should it require the user to prefix the symbols they want flipped with something like 'rtl_' in the layer name?

**Comment by fariadiego** [comment]
I'm already excited about the next release!
It's good to have a prefix or at least a way to choose only the symbols that I want to flip.
Not all the symbols need to be flipped.

**Comment by fariadiego** [comment]
Hey! Any update on that?

**Comment by mageframe** [comment]
Haven't been on top of actively maintaining this repo I'm afraid, open to PRs with updates though.

**Comment by mageframe** [comment]
Latest PR from @k1sina added symbol support. Closing as fixed.

**Comment by fariadiego** [comment]
OMG! It seems to work perfectly! It will save a lot of time for my design team!
Next week I have a big project to work on and it will help a lot!
Amazing update :)

**Comment by k1sina** [comment]
I'm happy that I could help you to speed up your project process. 😉
