### ISSUE TITLE
Support Sketch 53,54,55 plugin 

### ISSUE THREAD

**Issue by babakkamiyab** [devinmancuso/sketch-rtl#8]
sketch-rtl dosnt work  
my imac is  retina 4k . 21.5 inch , 2017
3.4GHz.corei5

i have test on all these versions
skech version 54 ( 76480) 
skech version 53
skech version 55

after select artboard and change that , there is no reaction . no error, no description. nothing.

**Comment by mageframe** [comment]
Could you confirm the following:

What version version of the plugin you are running?

I have 1.0.4 running on 55.2 on my MBP and it seems ok.

**Comment by jamescheung36** [comment]
Hi, 
I experience the same issue - which the plugin doesn't work. 

MBP, macOS 10.14.4
Sketch 53.2, sketch-rtl 1.0.4

**Comment by rebyld** [comment]
Hi, my plugin isn't working either.

Version 61.2 (89653), sketch-rtl 1.0.4

**Comment by mageframe** [comment]
Pushed a [new release (v1.0.5)](https://github.com/devinmancuso/sketch-rtl/releases/tag/1.0.5) with support for new layer types on Sketch 61+

Let me know if you're still having issues with specific layers once you update.
