### ISSUE TITLE
Support for Sketch version 55.x

### ISSUE THREAD

**Issue by muhammadsr** [devinmancuso/sketch-rtl#9]
Can't seem to have it work on Sketch 55.2 :(

**Comment by mageframe** [comment]
Could you confirm the following:

What version version of the plugin you are running?
What bugs are you seeing / which elements are not translating for you?

I have 1.0.4 running on 55.2 on my MBP and it seems ok at first glance...

**Comment by muhammadsr** [comment]
> Could you confirm the following:
> 
> What version version of the plugin you are running?
> What bugs are you seeing / which elements are not translating for you?
> 
> I have 1.0.4 running on 55.2 on my MBP and it seems ok at first glance...

Nvm, False alarm! I just downloaded the plugin version V1.0.3 for my Sketch version 55.2 and it seems to be working. I might have used an older plugin before.

**Comment by mageframe** [comment]
Great to hear! You should grab the [latest 1.0.4 build](https://github.com/devinmancuso/sketch-rtl/releases/tag/1.0.4) as there might be one or two compat issues between 1.0.3 and 55.2.
